redding/deas

lib/deas/template_engine.rb, test/unit/template_engine_tests.rb
This is so you can provide meaningful backtraces and file information
even when rendering content that has already been rendered by another
engine.
This came up when attempting to implement `compile` for deas-erubis.
It is nice to give a file name so any exceptions get nice backtraces.
Note: this also removes locals from the expected API.  Locals are 
only needed at the top-level engine as all local handling should
be handled with that engine (ie Erb or other).  Compiling with
downstream engines should be about converting a more convenient
markup (ie writing markdown with erb) to the needed markup.
=> have `compile` render api expect the template name

lib/deas/template_engine.rb, lib/deas/template_source.rb, test/unit/template_source_tests.rb
This updates the template source to look for any layouts on the
view handler and build nested blocks that render each template
file.  This allows for templates to yield in each layout template
and render layouts.
This also updates the template engine render api to expect a content
block.  This is needed so the template engines can pass the layout
render blocks to their render logic and implement yielding in their
templates.
See redding/deas-erubis#11 and redding/deas-nm#7 for reference on using (or not) this api.
=> template source: render honoring any view handler layouts

lib/deas/template_engine.rb, lib/deas/template_source.rb, test/unit/template_engine_tests.rb, test/unit/template_source_tests.rb
This updates the render API to support sending a content block to
source/engine partial calls.  Doing this removes the need for a
dedicated capture partial method as it is just a partial call with
a content block.
This also cleans up the API to formally allow passing content blocks
to both the `render` and `partial` methods at the source level.  The
runner doesn't expose this to the view handler as it doesn't make
sense.  However, engines can use this in their template helpers.
This is all part of standardizing a rendering API that allows for
creating specific template engines that support rich rendering.
Deas::Erubis will specifically take advantage of these APIs to
allow rich partial rendering.
@jcredding like we discussed, I need this in place and need to roll a version to do the test …
=> render API: remove `capture_partial` method

lib/deas/template_source.rb, test/unit/template_source_tests.rb
This is a small render optimization.  The goal is to limit the
somewhat expensive logic of globing files on disk that match the
template name, rejecting out irrelevent ones and choosing the first
matching one just in order to lookup a files extension.
With this implementation, the expensive logic is only run once per
template (on the first lookup).  This will improve every render
call as this lookup is done both at engine-selection time but also
when querying to know if there is an engine available for the template.
Note: this also adds a test to make sure `engine_for?` returns false
on missing template names.  This was missing in the original tests
and is all about better coverage.
@jcredding ready for review.  This is all private level logic so it isn't really _explicitly_ tested. …
=> cache template name extensions at the template source

lib/deas/template_source.rb, test/unit/template_source_tests.rb
This reworks the `engine_for?` method to just take an extension
as an argument.  It then adds an `engine_for_template?` method that
works like the prev engine for method did.
The goal here is to be able to query whether an engine has been
configured when you already know the extension while keeping the
old ability to query when you don't know the extension but know the
template.
@jcredding ready for review.  I can across this need while updating our application configurations to use the latest deas and deas-erubis stuff.
=> rework template source api for querying about configured engines

lib/deas/test_runner.rb, test/support/fake_sinatra_call.rb, test/support/view_handlers.rb, test/unit/test_runner_tests.rb, test/unit/view_handler_tests.rb
This is part of switching to the new render API.  This gets the
render args API inline with the actual api.  This also updates the
tests to be more to our conventions with using factory data.
=> update test runner render args to conform to new render API

lib/deas/deas_runner.rb, lib/deas/runner.rb, lib/deas/sinatra_runner.rb, lib/deas/test_runner.rb, lib/deas/view_handler.rb, test/support/view_handlers.rb, test/unit/deas_runner_tests.rb, test/unit/runner_tests.rb, test/unit/test_runner_tests.rb, test/unit/view_handler_tests.rb
This expands the render API to allow rendering templates on given
sources (ie from 3rd party sources).  This allows third party tools
to provide handler mixins that render their own templates from their
own sources under special circumstances.
This is part of switching off of Sinatra/Tilt for rendering.
=> add source render/partial methods to the view handler and runners

lib/deas/template_source.rb, test/unit/template_source_tests.rb
This is a simple rename.  This name better describes the intent and
purpose of this option.  It is the source that will be used to
render if no specific source is specified.
This is useful if configuring 3rd-party template sources.  You may
want to configure their sources to use your app's template source
by default so that any generic renders done within 3rd-party templates
behave the same as if they were done within your app.  A case for
this would be if a 3rd-party template needs to render app-specific
partials.
@jcredding this came up while testing the new render API on our apps.  This has no behavior changes - just renames to better communicate the purpose of the option.
=> template source: rename `default_template_source` engine option

lib/deas/test_helpers.rb, test/unit/test_helpers_tests.rb
This formally defaults the rack request/response/session when building
test runners using the test helpers.  Now that templates are rendered
in tests, deas should provide sane defaults for these as templates
may rely on their values.  Also, users shouldn't have to fake this
if their views rely on them being in place.
This also formally tests the test helpers.  Before we were just
implicitly testing them as they were used in the test suite itself.
@jcredding this came up when rendering templates in the test suites of our apps.  Ready for review.
=> default rack settings when building test runners

lib/deas/exceptions.rb, lib/deas/handler_proxy.rb, lib/deas/redirect_proxy.rb, lib/deas/route.rb, lib/deas/route_proxy.rb, lib/deas/router.rb, lib/deas/server.rb, test/support/routes.rb, test/system/rack_tests.rb, test/unit/exceptions_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/redirect_proxy_tests.rb, test/unit/route_proxy_tests.rb, test/unit/route_tests.rb, test/unit/router_tests.rb, test/unit/server_configuration_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
This updates the API for defining routes to allow routing the same
method/path combination to different handlers based on the type of
request.  The goal here is to support rendering both mobile and
desktop versions of the same route.
A side-effect of this api change is you are no longer *forced* to
specify a handler when defining your routes.  In this case Deas will
error nicely.  Another side effect is handling the "default" case.
This involves optionally setting a default request type and handling
the case when no default handler is specified.
Note: this cleaned up the router/route/proxy handling too.  There
was a lot of coupling and who-handled-what didn't make a lot of sense.
These objects have been updated to better reflect their intended
responsibilities.  The associated tests are …
=> router: api to route same meth/path to diff handlers based on request

lib/deas/router.rb, test/unit/router_tests.rb
This was missed when I added the original base url handling.  I noticed
this while reworking the router for request type handling.
The original base url handling was done in #122 and #126, for reference.
=> router: handler base urls on redirects

lib/deas/template_source.rb, lib/deas/view_handler.rb, test/unit/template_source_tests.rb, test/unit/view_handler_tests.rb
This is so you can use handler attributes to determine your layout
template paths.  This allows for dynamic layout templates based on
the nature of the request.
Note: this also changes the API of the layout method to no longer
take multiple paths.  It now expects either a single path or block.
This also removes the `layouts` alias.  Now, layouts just returns
the layouts that have been specified.  This is to simplify the layout
API now that it is taking procs.  Plus, the multiple layout template
path feature hasn't been used much in practice.
Note also: the view handler instance now has a `layouts` method that
returns the layout templates paths.  It handles instance eval'ing
the class layout procs against the handler instance.
=> view handlers: have `layout` DSL take procs that are instance eval'd

lib/deas/test_runner.rb, test/unit/deas_runner_tests.rb, test/unit/sinatra_runner_tests.rb, test/unit/test_runner_tests.rb, test/unit/view_handler_tests.rb
Response value better describes what is being returned.  Yes, it
is a return value of some sorts, but what's return value.  It could
be from the run method or it could be from a halt in the init method.
I proposing it is better to describe it more specifically as a
value that represents the type of response that would result from
this action.  Thus, `response_value`.
This deprecates the `return_value` method with a warning so that
pre-existing test code can be migrated to this new method.
Closes #170.  Note I can't call it `response` as this method is already in use by the base runner.
=> test runner: deprecate `return_value`; switch to `response_value`

lib/deas/test_runner.rb, test/unit/test_runner_tests.rb
Unlike halt, render, redirect and send file, these methods aren't
typically called so that there return values are the return value
of the `run!` method.  This means they build their args in the test
runner but you can never access those args and test that their
values have been set appropriately.
This switches to storing their values in the test runner and making
these methods so that you can get the values if they are called with
no args.  This will allow you to check their values after a handler
has been run using the test runner.
Closes #152.
=> test runner: allow spying on the content type, status and headers

lib/deas/json_view_handler.rb, test/unit/json_view_handler_tests.rb
This adds a special view handler that forces the content type to
`:json` and updates `halt` to return an empty json object body if
no custom body is specified.
The goal here is to make working with json handlers easier.  Some
http clients require that the body be valid json if the response
content type is json (or even if the request made requested json).
Halting by default returns an empty body which isn't valid json.
=> json view handler

lib/deas/server.rb, lib/deas/sinatra_app.rb, lib/deas/sinatra_runner.rb, lib/deas/test_runner.rb, test/support/fake_sinatra_call.rb, test/unit/server_configuration_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb, test/unit/sinatra_runner_tests.rb
This is some changes to how Deas handles content type.  The goal
is to have less coupling with Sinatra (in prep for moving off of
Sinatra in the future) and to have a more consistent experience using
and testing content type handling.
There are a number of changes here:
* remove `deas_default_charset` custom setting - this was a hacky
shim of a solution to to allow deas apps to specify default encodings
* rename `default_charset` config opt to `default_encoding` - this
name matches the sinatra setting is drives and is also more accurate.
* properly set sinatra's default encoding from the config opt
* add `application/json` to the mime-types that get charset info added
* remove custom logic in the sinatra runner `content_type` method for
applying charset.  Now that we are properly …
=> cleanup content type and default encoding handling

deas.gemspec, lib/deas/redirect_proxy.rb, lib/deas/router.rb, test/unit/redirect_proxy_tests.rb, test/unit/router_tests.rb
This was missed when I originally added the redirect base url logic
back in PR 172.  In that effort I took care of honoring the base
url on the incoming path, but not on the redirect path.
This logic adds handling for the redirect path side of things.  To
accomplish this, redirect proxies need to be passed a router so
they can prepend the router's base url when generating their redir
paths.
In addition, I updated the router tests to randomly have a base url 
set or not and to actually test the redirect paths that were being
produced.  The orig tests didn't do these things which contributed
to this logic being missed in the first place.  This involved adding
a `set_base_url` method allows manually resetting the base url to
`nil` since this can't be done wth the `base_url` method.
See #172, …
=> have redirects honor any router base url

lib/deas/server.rb, lib/deas/sinatra_app.rb, test/unit/server_configuration_tests.rb
This is prep for removing Sinatra as a dependency.  I want to mimic
Sanford's implementation as much as possible since they both involve
servers and requests/responses.
There are no behavior changes here - just code reorgs and indentation
changes that make the diff look horrible.  I wanted to get this
out of the way before making more pertinent changes.
@jcredding ready for review.  The other goal here is to get sinatra out of Deas' error handling.  I'm going to put this in a feature branch as there will be a few efforts needed to get this working.
=> reorg the server implementation code to better match Sanford

lib/deas/handler_proxy.rb, lib/deas/logging.rb, lib/deas/route.rb, lib/deas/server.rb, lib/deas/server_data.rb, lib/deas/sinatra_app.rb, test/support/factory.rb, test/support/fake_sinatra_call.rb, test/unit/error_handler_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/logging_tests.rb, test/unit/route_tests.rb, test/unit/server_data_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb, test/unit/sinatra_runner_tests.rb
This organizes some server attributes and makes them available to
the things processing the request: the route, handler proxies,
middleware, etc.  This goal here is to more closely match Sanford's
implementation and also take another step towards phasing out
Sinatra.
Right now, I'm choosing to only track the error procs, logger, router,
and template source.  As we phase out sinatra more, we can move over
additional server attrs.
This is prep for getting sinatra out of the error handling logic.
Note: this removes some legacy :erb settings.  These sould have
been removed back when template rendering was reworked but were
missed.
=> add server data object

lib/deas/error_handler.rb, lib/deas/handler_proxy.rb, lib/deas/server.rb, lib/deas/sinatra_app.rb, test/support/factory.rb, test/support/routes.rb, test/unit/error_handler_tests.rb, test/unit/handler_proxy_tests.rb
This updates the error handler to not depend on Sinatra.  This is
part of prepping to remove Sinatra from Deas.  This also gets Deas'
error handling more inline with how Sanford handles errors.  Ther
are three big differences this introduces.
First, error procs are no longer evaluated in Sinatra's scope.
Practically this means you can no longer do Sinatra-y things like
halting in your error procs.  Proc return values are still used
to alter responses but you'll have to treat these handlers more
like raw Rack and manually return the appropriate response values.
This also means that *all* error procs will always be run and the
last non-nil return value will always be used as the response.
Before, you could theoretically halt in an error proc and cutoff
any remaining error procs.
Second, …
=> remove Sinatra from the error handling process

lib/deas/logging.rb, test/support/fake_sinatra_call.rb, test/support/routes.rb, test/unit/logging_tests.rb
This updates the summary logging middleware to not error when it
is called and the env doesn't have a handler class. This happens
when an unknown route is called. Sinatra raises a not found error
and no handler class is set in the env.
This fixes the error by checking if the env key is set before
adding it to the line attrs. If there is no handler class, the
summary line will not contain a `handler`.
This also reworks the logging tests to fully test this logic.
Previously, we skipped fully testing our middleware because of the
setup required and because we were hurrying deas development.
Because of this, when the error was introduced the test suite
didn't error. This updates the tests to test more of the logging
middlewares logic and should help to avoid this happening in the
future.
As …
=> Update summary logging to not error without a handler class

lib/deas/show_exceptions.rb, test/unit/show_exceptions_tests.rb
This is a small set of cleanups to the show exceptions middleware
and its tests to match our latest conventions. This is part of
cleaning up our middlewares and testing them consistently.
This simplifies the `Body` helper. It doesn't need to lazily set
its content, size and mime type because we use all of them when we
build it. This also reorganizes the tests to match our latest
conventions and switches to using the fake sinatra call for the
middlewares app. This also adds a test to make sure the apps
response isn't modified if there isn't an error.
@kellyredding - Ready for review. This was the only other middleware we have in Deas. There are also system tests that test the show exceptions middleware already.
=> Cleanups for show exceptions and its tests

lib/deas/router.rb, test/unit/router_tests.rb
The router was missing a couple of cases where a named url could
be specified but not yet defined: the redirect from url and the
main router from url.  This cleans up the logic and adds tests to
cover these cases.
@jcredding ready for review.  Just a cleanup I noticed while working in the router on the not found directive and lazy named url eval.
=> router: properly complain about named urls that aren't defined

lib/deas/router.rb, lib/deas/server.rb, test/unit/router_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
This switches the router logic to lazily apply route definitions.
The goal here is to allow defining a route that uses named urls
without first having defined the named url.  Overall, the router
should not be picky about the order directives are specified as long
as everything is valid once all directives have been specified.
To facilitate this, the route now only stores the definitions for
routes when a route or redirect method is called.  These definitions
build up and can be converted to actual routes on the router by
calling the `apply_definitions!` method.  The server now auto applies
definitions during its validation.
Note: to simplify the server and require it to know as little about
the router as possible, I chose to add a `validate!` method to the
router that the server now …
=> router: lazy apply routes definitions

lib/deas/respond_with_proxy.rb, lib/deas/router.rb, test/unit/respond_with_proxy_tests.rb, test/unit/router_tests.rb
These routes will always respond with a 404.  Allows you to 404
known paths without relying on Sinatra to raise a `Sinatra::NotFound`
error.
This follows the pattern of the redirect definition.
=> router: add `not_found` route definition

lib/deas/exceptions.rb, lib/deas/logging.rb, lib/deas/show_exceptions.rb, lib/deas/sinatra_app.rb, test/support/factory.rb, test/support/routes.rb, test/system/rack_tests.rb, test/unit/exceptions_tests.rb, test/unit/logging_tests.rb, test/unit/show_exceptions_tests.rb
This is another small piece in prep for removing Sinatra as a
dependency.  This does a few things:
* replaces `Sinatra::NotFound` exception handling with `Deas::NotFound`
* includes the path info in the not found exception message
* makes the exception factory randomly generate with `nil` backtraces
as we've seen this come up in production
* make the error handling tolerate exceptions with `nil` backtraces
gracefully
Overall, this is about removing sinatra usage.  In addition we get
the benefit of not found exceptions that actually include the path
that wasn't found (which is really helpful when debugging or when
these come up in production).
=> remove usage of `env['sinatra.error']` and `Sinatra::NotFound`

lib/deas/sinatra_runner.rb, test/unit/sinatra_runner_tests.rb
These params are side-effects of using Sinatra under the covers
and aren't intended features we want to support.  This removes them
now so they won't be relied upon when we remove Sinatra at a later
date.
This is prep for removing Sinatra as a dependency.
=> remove 'splat' and 'captures' from params in SinatraRunner

lib/deas/handler_proxy.rb, lib/deas/runner.rb, lib/deas/test_runner.rb, lib/deas/view_handler.rb, test/support/routes.rb, test/system/rack_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/runner_tests.rb, test/unit/test_runner_tests.rb, test/unit/view_handler_tests.rb
This effectively means you can't do direct rack response manipulation
in the handlers.  You must use a helper (ie status, headers, body, halt,
etc).
This is prep for adding a `response` handler helper for setting
responses (similar to `halt` except it won't halt execution).  This
helper will be how response data is set and will deprecate the
run-return-value-gets-set-as-the-response behavior.
Related to #174 
=> remove `response` as a handler/runner attribute

lib/deas/server.rb, lib/deas/template_source.rb, test/support/factory.rb, test/support/fake_request.rb, test/support/fake_sinatra_call.rb, test/support/routes.rb, test/system/deas_tests.rb
This cleans up the system tests to get them up to our latest standards
and to get them all running/passing as intended.  The biggest change
is certain tests weren't returning a 200 status but we didn't assert
this and the other thing being tested just *happened* to pass but
wasn't passing b/c of the thing under test.
This is prep for removing sinatra from the response handling.  Sinatra
is the cause of the test *happening* to pass and this was exposed
when Sinatra was removed from response handling.
=> cleanups to the system tests

lib/deas/redirect_proxy.rb, test/unit/redirect_proxy_tests.rb, test/unit/router_tests.rb
This is more proper and better aligns with the header name that
redirects affect.  This is a cleanup in prep for removing Sinatra
from response handling.
=> redirect proxy: rename "path" to "location"

lib/deas/view_handler.rb, test/unit/view_handler_tests.rb
These reorganizes the private helper methods to group them by
their function.  This also updates the tests to get them up to our
conventions and to actually unit test the private helpers.  This
adds a bunch of tests that should have been in place originally but
were missed.
This was noticed while removing Sinatra from response handling.  This
just adds "noise" to that future effort so I'm breaking it off in
this PR to keep that coming effort as focused as possible.
=> prep view handler for removing Sinatra from response handling

lib/deas/deas_runner.rb, lib/deas/handler_proxy.rb, lib/deas/runner.rb, lib/deas/sinatra_runner.rb, lib/deas/test_runner.rb, test/unit/deas_runner_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/runner_tests.rb, test/unit/sinatra_runner_tests.rb, test/unit/test_runner_tests.rb
This are some random things I discovered are needed to help remove
Sinatra from response handling.  They essentially just add "noise"
to that coming effort so I want to break them off in their own
PR to keep the coming effort as focused as possible.  They include
* minor style cleanups and updates to get tests on latest conventions
* moving the logic for removing splat/captures params into the
handler proxy and out of the sinatra runner as the sinatra runner
will be removed in the coming effort
* order args consistently in code as they flow from handler proxy to
runner (or test runner)
=> minor cleanups to prepare for removing Sinatra from response handling

lib/deas/view_handler.rb, test/unit/view_handler_tests.rb
This allows you to implement all run related behavior in callbacks
only if you choose.  This is ideal if you need to put run logic
into handler mixins but want to use callbacks b/c you aren't sure
what other handler mixins may be in play.
=> view handler: make default `run!` method a no-op

lib/deas/deas_runner.rb, lib/deas/test_runner.rb, lib/deas/view_handler.rb, test/unit/view_handler_tests.rb
Since view handlers are intended to run user code, we want to be
careful to not "pollute" the handler scope with our own methods
that will break in spectacular ways if the user happens to override
them.
This switches all the internal methods (ie methods not intended to
be called or used by users) to be prefixed with `deas_`.  This not
only marks them as internal "deas" methods but also makes it more
difficult to accidentally override in custom user handlers.
In addition, now that the methods are namespaced, I have no problem
making the `deas_run_callback` method public.  This allows the
deas runner to call the method directly instead of instance eval
calling it (which feels unnecessarily hackish).
=> view handler: namespace non-user-facing methods

lib/deas/test_runner.rb, test/unit/test_runner_tests.rb
This allows you to test that your handler called `content_type`
without having to worry about the details of what calling content
type does.  This essentially spies on content type calls.
This came up when testing the latest Deas changes in deas-json.  That
gem sets `.json` content type and needs to test that this has been
done.
=> test runner: capture content type args

lib/deas/template_source.rb, test/unit/template_source_tests.rb
This updates template sources to pass the extension that was used
to register an engine to the engine as an option. The goal is to
allow the engine to choose templates that match the extension that
was used when configuring the extension. This is also part of
fixing an issue with the engines not knowing which template file
to pick because they no longer hard-code an extension that the
templates have to use.
The template source now always sets an ext option and passes it
to the engines when they are registered. The ext will always be
set and can't be different from how the engine is registered. It
would be non-sensical to register with one engine ext and pass a
different engine ext as an option. Deas would either not use
the registered engine to render the template or the template
engine …
=> template source: pass ext as an option to registered engines

lib/deas/template_source.rb
The goal here is to create less objects and avoid having to modify
variable state.  This drops the `dup` and `shift` operations in
favor of more functional approaches using `drop(1)` and `first` to
get the necessary parts of the extension list.  I like this better
b/c it doesn't mutate state and doesn't require adding a local var.
The tests don't change and everything works as it did before.  There
doesn't seem to be any performance impact either.
@jcredding ready for review.  Are you cool with this change?  Am I missing anything about this that might impact performance or otherwise be problematic?
=> template source: minor optimization to private `compile` logic

lib/deas/template_source.rb, test/support/template-compiled3.foo.json, test/support/template-compiled4.json.foo, test/unit/template_source_tests.rb
Previously, we just blindly rejected all un-registered template exts.
This is nice b/c it means we don't incur the overhead of running
through the null engine repeatedly for the un-registered exts.
However, some engines require that source files end in their configured
ext when doing the initial render.  For example, say you have a template
named `template.erb.foo`.  The erb engine requires that its source
files end in `.erb`.  Without this change, `.foo` would get rejected
and the erb engine would be used to source render the file.  But the
engine would error b/c the file doesn't end in `.erb`.  None of this
makes sense to the user who just expects Deas to "ignore" unregistered
extensions.
With this change, the `.foo` ext in the example above is not rejected
which means the null template …
=> templates: don't reject unregistered exts if they are the last ext on the file

lib/deas/template_source.rb, test/unit/template_source_tests.rb
This minor optimization will now cache null template extensions.
The idea is to not repeatedly call the engine cache default block
for known null extensions.
To make this possible, I had to update the logic for determining
if we have a registered engine.  We now store a separate list of
registered extensions. This implementation is nice b/c it decouples
the engine cache from defining whether an engine is registered or not.
This will be helpful once PR 209 is merged as templates ending with
null extensions will won't have those extensions removed from their
extension list and would otherwise incur the overhead mentioned
above.
See #209 for reference.
=> templates: cache null template engines on known null extensions

deas.gemspec, lib/deas.rb, lib/deas/server.rb, lib/deas/server_data.rb, lib/deas/sinatra_app.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
We are moving away from using ns-options as a dependency b/c it
has performance issues when accessing options and on top of that
its API hasn't proven to be especially useful over a struct-like
class.
This removes ns-option and reworks the server, its config and the
sinatra app to support the non-ns-options config implementation.
The config is now a simple struct-like class with a bunch of
accessors for its attrs.  The server class methods now implement
the ns-options-like DSL api for each of their attrs for backwards
compatibility.
In addtion, I did a number of smaller changes/cleanups, including
some thing that aren't backwards compatible:
* switched to calling the config "config" (more succinct than prev
with no loss of clarity).
* you can no longer set config values to procs (for lazy …
=> remove ns-options dependency

deas.gemspec, lib/deas/runner.rb, lib/deas/test_runner.rb, test/unit/respond_with_proxy_tests.rb, test/unit/runner_tests.rb, test/unit/url_tests.rb
This is prep not only for removing Sinatra as a dependency but also
fixes some bugs in modern ruby versions (ie non-1.8.7).  In 1.8.7,
`String` responds to `each` but in modern versions it does not.  This
change now forces the body values to always respond to `each` (per
Rack spec) by forcing string bodies to be transformed to arrays. As
a side-effect, the `:each` check and custom exception was removed.
This also does a number of minor tweaks related to this change and
also to get the test suite passing in modern ruby versions:
* update to the latest assert patch - this version has a minor fix
for modern ruby versions
* `halt` now *assumes* any arg after the status and headers checks
is the body value - no need to perform the `:each` check as it
is unreliable for string bodies
* the …
=> updated body handling to better adhere to Rack standard

lib/deas/router.rb, lib/deas/url.rb, test/unit/router_tests.rb, test/unit/url_tests.rb
This is prep for a coming feature where the router's `url_for` method
will start complaining if "empty" param values are given.  We have
to first stop allowing ordered param values b/c when ordered values
are applied we don't know if they are being applied for a named
param or not.  This change breaks backwards compatibility.
This not only removes taking arbitrary ordered params in `url_for`,
it also makes the method complain if param values aren't given in
Hash form.  This new implementation would error in weird ways as
it expects a hash to be given.  This makes the error message more
friendly.
=> urls: stop taking ordered param values for the router's `url_for` method

lib/deas/router.rb, lib/deas/url.rb, test/unit/router_tests.rb, test/unit/url_tests.rb
Empty (ie `nil` or empty string) values aren't valid for named param
values as urls with named params are never matched on empty values
(the route just won't match at all).  Therefore it is silly to
build urls with empty values as they will never be matched.
This switches the `url_for` method on the Router to now complain
if given an empty named param value.  The goal here is to give the
developer some warning that they are building a non-sensical url
value.  Note: this doesn't apply to splat param values or any "extra"
param values (which are added to the query string).  This only
applies to formally named params in the url path.
=> urls: have `url_for` complain if passed empty values for named params

lib/deas/server.rb, test/unit/server_tests.rb
This allows for reading config values via the server directly as
the server tries to abstract its config.  Since the other DSL
methods map one-to-one with their config values, they are their
own readers.  This covers the config settings that aren't driven
by a direct DSL method.
@jcredding ready for review.  This came up when testing Deas in our apps.
=> server: demeter config values that aren't directly set

lib/deas/handler_proxy.rb, lib/deas/router.rb, lib/deas/runner.rb, lib/deas/test_runner.rb, lib/deas/url.rb, lib/deas/view_handler.rb, test/unit/handler_proxy_tests.rb, test/unit/router_tests.rb, test/unit/runner_tests.rb, test/unit/test_runner_tests.rb, test/unit/url_tests.rb, test/unit/view_handler_tests.rb
This reworks splat handling in Deas.  Originally, Deas handled
splats just as Sinatra would.  However, the plan was never to
support the full splat flexibility of Sinatra's splats in Deas'
upcoming Sinatra-free implementation.
So, back in PR 181, we removed both the splat and any "captures"
from the params Sinatra provided.  The router (being Sinatra's)
still honored splat routes but you couldn't access the splat
values in the params.  This was Step 1 in getting away from the
Sinatra splat implementation.
However, there are undeniable uses for splats and it was a little
naive to assume that no splat handling is acceptable for Deas.
This effort is an attempt to take the best parts of Sinatra's
splat handling and provide that in Deas.  This comes in the form
of two features:
* limit splats …
=> formalize restricted splat handling

deas.gemspec, lib/deas/handler_proxy.rb, lib/deas/request_data.rb, lib/deas/route.rb, lib/deas/runner.rb, lib/deas/server.rb, lib/deas/sinatra_app.rb, lib/deas/test_runner.rb, lib/deas/view_handler.rb, test/support/factory.rb, test/support/fake_request.rb, test/support/fake_response.rb, test/support/fake_sinatra_call.rb, test/support/routes.rb, test/system/deas_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/request_data_tests.rb, test/unit/route_tests.rb, test/unit/runner_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb, test/unit/test_runner_tests.rb, test/unit/view_handler_tests.rb
This is prep for removing Sinatra as a dependency in the future.
This not only removes Sinatra from the request handling but also
decouples the rack app implementation from request handling by
introducing the concept of "request data" and passing that
between the rack endpoint and the runner/handler.
So, this creates a RequestData struct.  Right now the request data
consists of the request, response, params and route path.  The
route path is being added to not only have for logging/error usage
but to also use in a coming effort to take over splat handling.
I chose to remove manual session handling as you can access the
session info on the request and I don't want deas to support
manual session handling going forward.
Note: this removes `sessions` handling form the server api and
its …
=> remove Sinatra from route/request handling

lib/deas/sinatra_app.rb, test/support/routes.rb, test/system/deas_tests.rb, test/unit/sinatra_app_tests.rb
This is prep for removing Sinatra in a future effort.  This
switches to rescuing StandardError on route runs instead of
configuring a sinatra error handler.  This takes Sinatra out of
the error handling logic.  Sinatra had already been removed from
the error handler class itself so this change is fairly trivial.
There is one small side-effect of this change: only a set of
"standard error" exceptions are rescued (which is different than
Sinatra's default of all exceptions).  The intent is that any
errors you would handle should already be StandardErrors as non
standard errors include system interrupts etc which are dangerous
to rescue as this may alter system behavior.  We include a few
common non-standard errors that can be expected to occur.  The
system tests have been updated to account …
=> take over error handling fully from Sinatra

lib/deas/error_handler.rb, lib/deas/request_data.rb, lib/deas/sinatra_app.rb, test/support/factory.rb, test/unit/error_handler_tests.rb, test/unit/request_data_tests.rb
Since we are now passing this data to the runner/handler
(see PR 219), it would be nice to also make it available in the
error handler context data.  Some applications include getting
extra context on where params are coming from and knowing which
route caused the error (in the case where multiple route paths
route to the same handler).
Note: I reorder the route path in the request data and where it
is used to keep things more consistently ordered.
See #219 for reference.
=> add the route path to the error handler context data

lib/deas/router.rb, test/unit/router_tests.rb
Back in PR 217, Deas was updated to restrict splats in route path
definitions to only allow trailing splats.  In that effort the
check was applied to named urls that were defined but if the route
didn't use a named url, the check was missed.  This moves that
error check to where the routes are added.  This way, no matter
where the path comes from, the check will be performed.
This also adds a new check to ensure named urls are defined with
symbols.  Before, any given name would be turned into a symbol
so if you defined a named route with a string you'd have to know
to refer to it with a symbol.  This removes that magic knowledge
requirement and just warns you if you aren't using symbols when
defining named urls so there won't be any confusion when you go
to use that named url.
See #217 …
=> update router route error checking to be more thorough

lib/deas/error_handler.rb, lib/deas/handler_proxy.rb, lib/deas/logging.rb, lib/deas/sinatra_app.rb, test/unit/error_handler_tests.rb, test/unit/handler_proxy_tests.rb, test/unit/logging_tests.rb
This makes the splat value (if any) available to error handlers
as contextual info.  Since splats are no longer part of the params
we need a way to access this info in error handlers.
This also updates the handler proxy to store the splat value on
the request env.  This makes it available to middlewares.  The
also updates the logging (includeing the Logging middleware)to use
the splat info in their logs.  I chose to also log the route path
in the verbose logs for completeness (this should have been done
in previous efforts).
Note: I updated the error context to "fetch" its attrs from the
given args hash.  This is to enforce that if the context expects
a value the rack app supplies it.  This also closes a gap in our
tests and tests that the rack app is creating the context as
necessary. …
=> add splat value to middlewares and error handler context info

lib/deas/handler_proxy.rb, lib/deas/runner.rb, lib/deas/test_runner.rb, test/unit/handler_proxy_tests.rb, test/unit/runner_tests.rb, test/unit/test_runner_tests.rb
This is prep for removing Sinatra from Deas.  We no longer want
to rely on Sinatra to parse splat values for us.  This switches
to manually parsing it using request data.  This also means the
base runner is no longer given a splat value.  The test runner
however continues using its given splat value similar to how it
uses any given params value.
Note: this may be altered if our custom router someday parses
splats for us.
=> parse splat values from the PATH_INFO and route path data

lib/deas/url.rb, test/unit/url_tests.rb
This fixes a bug where if you happen to define a url with param
names that compose another params' names, the url generation will
not set the param names correctly.  This updates the tests to
test this case and updates the implementation to apply longer
param names before shorter param names.
I discovered this problem while working on PR 224.
See #224 for reference.
=> update url generation to work with composed param names

lib/deas/server.rb, lib/deas/sinatra_app.rb, test/support/routes.rb, test/unit/router_tests.rb, test/unit/server_tests.rb
This is not something we want to support going forward.  The only
reason we supported it in the first place is b/c we originally
based Deas on Sinatra and Sinatra supported it.  This is prep
for removing Sinatra from Deas.
=> remove the settings Server API

lib/deas/request_data.rb, lib/deas/server_data.rb, test/unit/request_data_tests.rb, test/unit/server_data_tests.rb, test/unit/sinatra_app_tests.rb
This cleans up some tests in the SinatraApp.  I noticed this
while prepping to remove Sinatra.  The RequestData doesn't need
this logic right now but I'm adding it to be consistent.  I also
made the ServerData require args always be passed.  This is, again,
for consistency sake.
=> add equality operator handling to ServerData and RequestData

lib/deas/server.rb, lib/deas/sinatra_app.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
This is part of prepping Deas to remove Sinatra.  This removes
some configs and changes others to disable most of Sinatra's
default behavior.  This is to ensure we aren't unknowingly relying
on Sinatra prior to removing it.
A few notes:
* I kept the `env` and `root` settings.  The root setting is used
by Deas to default the template source, but more importantly,
these provide a nice common interface to this data for gems that
extend deas behavior.
* I am keeping the `method_override` setting b/c I'm not sure how
I want to handle this in Deas once Sinatra is gone.  The behavior
most likely will need to be manually implemented so it seems
likely we'll want to be able to turn it off/on.
* I chose to set the `views` and `public_folder` setting to the
root just b/c they make nice benign …
=> remove Sinatra settings we don't want to support going forward

lib/deas/logging.rb, lib/deas/server.rb, lib/deas/sinatra_app.rb, test/unit/logging_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
This is prep for removing Sinatra.  All Sinatra did was add
`Rack::MethodOverride` to the middleware stack if the option was
set.  This does the same thing, prepending it as Sinatra did.
=> manually handle the `method_override` server config

lib/deas/route.rb, lib/deas/server.rb, lib/deas/server_data.rb, lib/deas/sinatra_app.rb, test/unit/route_tests.rb, test/unit/server_data_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
This allows adding before/after route run procs when configuring
a server. These are needed for logic that you want to run before
or after every route but not run for every request via a
middleware. These will also run even if there is an exception.
This is specifically useful for adding logic to check in
activerecord connections after a route has been run in a threaded
environment. This doesn't need to run for requests that are
terminated by a middleware that never uses activerecord but it
needs to run for every route which has a high chance of using
activerecord.
A `Route` will now call before and after route run procs when its
run. It gets the procs from its `ServerData` and uses an `ensure`
to run the after procs. This means the procs will run even if an
exception occurs while running …
=> Allow adding before/after route run procs

lib/deas/runner.rb, test/unit/runner_tests.rb
See www.rubydoc.info/github/rack/rack/master/file/SPEC#The_Body.
"The Body must respond to each and must only yield String values".
This is a minor tweak to for any single values into an array
*of strings* (since the body must yield strings).  We still want
to support allowing specifying bodies with single objects from the
Deas API point-of-view.  This just makes sure we are properly
adhering to Rack's spec.
I added comments to the code to help explain this so we are aware
in the future.
=> update the `body` helper to properly implement the Rack spec

lib/deas/sinatra_app.rb, test/system/deas_tests.rb
This is to give more context on the error and why it is not found.
You may have routed the path but not with the method and that is
why it is not found.
The error looks something like this:
```
GET /not-found-path
(backtrace...)
```
=> return the request method in Deas::NotFound error messages

lib/deas/error_handler.rb, lib/deas/logging.rb, lib/deas/server.rb, lib/deas/sinatra_app.rb, test/support/fake_sinatra_call.rb, test/unit/logging_tests.rb, test/unit/server_tests.rb, test/unit/sinatra_app_tests.rb
So previously I had said that there was no good way to get server
config args to the middlewares except to store those on the
Sinatra app since this "app" was what was initialized with each
middleware.  Well, turns out I was wrong.
First off, the "app" initialized with each middleware is really
more like the "next upstream middleware or the end app".  I get
why the convention is to call it "app" b/c from the middleware's
point of view it might as well be the app, but this had confused
me.  Second, there is an interface for passing args to middlewares.
Sinatra's `use` takes the same `Rack::Builder` interface which
means both `*args` and a proc can be passed.  They just need to
be specified as addition params.
So, this switches to using this interface and also switches to
directly passing …
=> cleanup middleware args handling

lib/deas/router.rb, test/unit/router_tests.rb
This adds 3 new router api methods: `require_trailing_slashes`,
`require_no_trailing_slashes`, and `allow_trailing_slashes`.
Calling any of these methods will set a "trailing slashes" config
setting value on the router that will direct it how to handle
trailing slashes in its routes.  The goal with this is to help
prevent unnecessary 404s b/c a user (or the browser) accidentally
adds/omits a trailing slash on a URL path.
First let's look at `require_trailing_slashes`.  This is intended
when you want all of your paths to end in a trailing slash.  The
router will ensure this and error if it finds routes not ending
in a slash when validating.  In a future effort, this directive
will also force-redirect any paths not ending in a slash to end
in a slash.
`require_no_trailing_slashes` does the …
=> update the router api for setting trailing slashes handling

lib/deas/runner.rb, lib/deas/view_handler.rb, test/unit/runner_tests.rb, test/unit/view_handler_tests.rb
This is a helper method for setting cookie headers.  It uses
`Rack::Utils.set_cookie_header!` under the covers but its api is
different.  It takes a cookie name, cookie value, and cookie
options.  It passes its own `self.headers` to the rack utils
method for making sure the headers are updated.
We chose this API as it is more defined and explicit compared to
the rack utils method (so it will be easier to support and
document).  It also makes more intuitive sense as a cookie has
a name and value.  The options allow you to pass the same options
you would to the rack utils method to control and secure the
cookies.  This just provides a defined api and abstraction for
the rack utils implementation so we can change it as needed with
minimal app impact.
=> add view handler `set_cookie` private helper

lib/deas/router.rb, test/unit/router_tests.rb
This adds `allow_trailing_slashes_set?` and
`remove_trailing_slashes_set?` predicate methods for helping test
whether your router has been configured properly.  This keeps you
from having to know the actual value the trailing slashes property
was set to (b/c it is unimportant) or the internal directive
constants (b/c they are just intended for internal use.
This also adds tests for the previously added
`trailing_slashes_set?` predicate method.  I originally missed
adding these in PR 239.
See #239 for reference.
=> add predicate methods for testing trailing slash directives

lib/deas/runner.rb, test/unit/runner_tests.rb
This is a set of updates to how the response body is defaulted and
handled when called with "empty" values.  The goal of all of this
is that the default response body will be used unless a meaningful
alternative response body has been given.
First off, this updates the default body to, formally, be an array
with a single empty string as this more accurately conforms to
Rack's spec that body objects must yield string values.
Next, this updates the `body` helper to ignore `nil` and empty
string values as they have no value and are identical to the
default body in intent.
Finally, this updates the halt method to also ignore `nil` and
empty string values for similar reasons as above.
=> improved default response body handling

lib/deas/runner.rb, lib/deas/view_handler.rb, test/unit/runner_tests.rb, test/unit/view_handler_tests.rb
This allows individual handlers to override the default response
values for status, headers, and body in a reliable manner.
Specifically, this will be used in Deas-Json to override the
default body for its needs.
First this moves the status/headers/body defaults to the view
handler.  This also adds the DSL singleton methods for overriding
the defaults on a per handler basis.
Second, this reworks the runner logic to look to the given handler
class for the default values.
Note: to make this happen, I had to do two other things:
* I had to commonize the logic for setting body response values.
This logic applies both for setting handler instance response
bodies and handler-specific default response bodies.
* I had to rework some of the test contexts to work with the new
singleton handler …
=> add a handler DSL api for setting default response values
